import Head from 'next/head';
import Nav from './nav';

export default function Layout({ children, page }) {
  return (
    <div className="p-0 bg-gradient-to-tl from-slate-800 to-sky-900">
      <Head>
        <title>ZK Auction House</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <header className="">
        <Nav page={page} />
      </header>
      <main className="min-h-screen py-8 px-0 flex flex-col flex-auto items-center">
        {children}
      </main>
    </div>
  );
}
